version: "3"
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/usr/site
      - /usr/site/node_modules
    environment:
      - PORT=80
      - NODE_ENV=development

  front-balancer:
    image: nginx:alpine
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "80:80"
    volumes:
      - ./config/front-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site/static:/var/www/static
    depends_on:
      - site
